### ISSUE TITLE
[SATOSA-oidcop] basic auth on token endpoint does not work

### ISSUE THREAD

**Issue by melanger** [IdentityPython/oidc-op#141]
I am trying to use the new OIDC frontend for SATOSA (`pip install satosa_oidcop`). When calling the token endpoint for exchanging an authorization code for an access token, using basic auth, it fails here:

https://github.com/IdentityPython/oidc-op/blob/754385f4db6348a2ed4472e9b10bfb47c20c9bee/src/oidcop/client_authn.py#L108

This line throws an exception, because `self.server_get("endpoint_context").cdb` is empty (`{}`). I found out that the frontend did not use mongodb storage at all with this config:

```
storage:
    class: "satosa.frontends.oidcop.storage.mongo.Mongodb"
    kwargs:
      url: "mongodb://host1,host2,host3/?authSource=satosa&replicaSet=production&tls=true&tlsCAFile=/usr/share/ca-certificates/extra/chain.crt&tlsCertificateKeyFile=/opt/certificate_and_key.pem"
      connection_params:
        username: "user"
        password: "pass"
    db_name: "satosa"
    collections:
      session: session
      client: client
```
I had to change it to this:

```
storage:
    class: "satosa_oidcop.core.storage.mongo.Mongodb"
    kwargs:
      url: "mongodb://host1,host2,host3/?authSource=satosa&replicaSet=production&tls=true&tlsCAFile=/usr/share/ca-certificates/extra/chain.crt&tlsCertificateKeyFile=/opt/certificate_and_key.pem"
      connection_params:
        username: "user"
        password: "pass"
    db_name: "satosa"
    collections:
      session: session
      client: client
op:
    server_info:
      client_db:
        class: "satosa_oidcop.core.storage.mongo.Mongodb"
        kwargs:
          storage_conf:
            db_name: "satosa"
            collections:
              session: session
              client: client
          url: "mongodb://host1,host2,host3/?authSource=satosa&replicaSet=production&tls=true&tlsCAFile=/usr/share/ca-certificates/extra/chain.crt&tlsCertificateKeyFile=/opt/certificate_and_key.pem"
          connection_params:
            username: "user"
            password: "pass"
```

Now it gets past the basic auth, it logs

https://github.com/IdentityPython/oidc-op/blob/a87177e7a5d0b40dcff11ed75b39a72bd2d3f015/src/oidcop/oauth2/authorization.py#L797

but then fails with:

```
{'error': 'server_error', 'error_description': "'dict' object is not callable", 'state': '...'}
```

which might be thrown from here:

https://github.com/IdentityPython/oidc-op/blob/a87177e7a5d0b40dcff11ed75b39a72bd2d3f015/src/oidcop/oauth2/authorization.py#L840
